BOARD_TAG = mega2560
ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH += $(realpath ../lib)
ARDUINO_LIBS += ros_lib
ARDUINO_LIBS += Encoder
ARDUINO_LIBS += ros
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=/usr/share/arduino
AVR_TOOLS_DIR=/usr
AVRDUDE=/usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
MONITOR_PORT=/dev/ttyACM0
include /usr/share/arduino/Arduino.mk
