#!/bin/bash
if [ -e /dev/ttyACM0 ]
	then
	sudo chmod 666 /dev/ttyACM0
		gnome-terminal -e "bash -c \"./roscore; exec bash\""
		sleep 2
		gnome-terminal -e "bash -c \"./python; exec bash\"" 
		sleep 2
		gnome-terminal -e ./keyboard &
	else
		echo "Arduino or joystick not connected or not added to virtual machine"
		exit
fi
