ARD_TAG =    uno
USER_LIB_PATH += $(realpath ../lib)
ARDUINO_LIBS += Wire
ARDUINO_LIBS += ros
ARDUINO_LIBS += TinyGPS++
ARDUINO_LIBS += SoftwareSerial
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=/usr/share/arduino
AVR_TOOLS_DIR=/usr
AVRDUDE=/usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
include /usr/share/arduino/Arduino.mk
